LuxuryHotel/Areas/Reception/Controllers/ImageController.cs
using LuxuryHotel.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LuxuryHotel.Areas.Reception.Controllers
{
    [Authorize]
    public class ImageController : Controller
    {
        // GET: Reception/Image
        private dbDataContext db = new dbDataContext();

        public ActionResult Index()
        {
            return View();
        }
        
        public JsonResult GetRoomImages()
        {
            try
            {
                var rooms = db.ROOMs
                    .Select(r => new
                    {
                       RoomID= r.RoomID,
                       RoomName= r.RoomName,

                    })
                    .ToList();
                return Json(new { code = 200, rooms = rooms, msg = "Lấy danh sách phòng thành công" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new { code = 500, msg = "Lấy danh sách phòng thất bại: " + e.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        
        public JsonResult GetUrlImagesByRoom(int roomID)
        {
            try
            {
                var images = (from ru in db.Images
                                 where ru.RoomID == roomID
                                 orderby (ru.OderID)
                                 select new
                                 {
                                     ImagePath = ru.ImagePath,
                                     
                                 }).ToList();

                return Json(new { code = 200, images = images, msg = "Lấy thông tin ImagePath thành công" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new { code = 500, msg = "Lấy thông tin ImagePath thất bại: " + e.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpGet]
        public ActionResult Edit(int roomID)
        {
            ViewBag.roomID = roomID;
           
            return View();
        }
        [HttpGet]
        public ActionResult GetImages(int roomID)
        {
            try
            {
                var images = (from ru in db.Images
                              where ru.RoomID == roomID
                              orderby (ru.OderID)
                              select new
                              {
                                  ImageID=ru.ImageID,
                                  ImagePath = ru.ImagePath,
                                  OderID=ru.OderID,

                              }).ToList();

                return Json(new { code = 200, images = images, msg = "Lấy thông tin ImagePath thành công" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new { code = 500, msg = "Lấy thông tin ImagePath thất bại: " + e.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(FormCollection f, HttpPostedFileBase fFileUpload)
        {
            try
            {
                // Kiểm tra nếu file và RoomID hợp lệ
                if ( ModelState.IsValid)
                {
                    // Lấy tên file
                    var sFileName = Path.GetFileName(fFileUpload.FileName);

                    // Lấy đường dẫn lưu file
                    var path = Path.Combine(Server.MapPath("/Admin/Images/Room"), sFileName);

                    // Kiểm tra ảnh đã tồn tại chưa để lưu lên thư mục
                    if (!System.IO.File.Exists(path))
                    {
                        fFileUpload.SaveAs(path);
                    }

                    // Tạo mới đối tượng Image
                    LuxuryHotel.Models.Image images = new LuxuryHotel.Models.Image
                    {
                        RoomID = int.Parse(f["roomID"]),
                        ImagePath = sFileName,
                        OderID = int.Parse(f["iOderID"]),
                    };

                    // Thêm vào CSDL
                    db.Images.InsertOnSubmit(images);
                    db.SubmitChanges();

                    return Json(new { code = 200, msg = "Tạo mới hình ảnh thành công" });
                }

                return Json(new { code = 404, msg = "Tạo mới hình ảnh thất bại. Vui lòng kiểm tra lại dữ liệu đầu vào." });
            }
            catch (Exception e)
            {
                System.Diagnostics.Trace.WriteLine("Error: " + e.Message);
                // Xử lý lỗi và trả về thông báo lỗi
                return Json(new { code = 500, msg = "Lỗi khi tạo mới hình ảnh: " + e.Message });
            }
        }

        [HttpPost]
        public ActionResult DeleteImage(int imageID)
        {
            try
            {
                // Kiểm tra xem có hình ảnh với ID cần xóa không
                var imageToDelete = db.Images.SingleOrDefault(i => i.ImageID == imageID);

                if (imageToDelete == null)
                {
                    return Json(new { code = 404, msg = "Không tìm thấy hình ảnh để xóa." });
                }

                // Lấy đường dẫn ảnh để xóa file từ thư mục
                var imagePath = Path.Combine(Server.MapPath("/Admin/Images/Room"), imageToDelete.ImagePath);

                // Xóa ảnh từ CSDL
                db.Images.DeleteOnSubmit(imageToDelete);
                db.SubmitChanges();

                // Xóa file ảnh từ thư mục
                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }

                return Json(new { code = 200, msg = "Xóa hình ảnh thành công." });
            }
            catch (Exception e)
            {
                // Xử lý lỗi và trả về thông báo lỗi
                return Json(new { code = 500, msg = "Lỗi khi xóa hình ảnh: " + e.Message });
            }
        }

        [HttpPost]
        public ActionResult UpdateOderID(int imageID, int oderID)
        {
            try
            {
                // Kiểm tra xem có hình ảnh với ID cần cập nhật không
                var imageToUpdate = db.Images.FirstOrDefault(i => i.ImageID == imageID);

                if (imageToUpdate == null)
                {
                    return Json(new { code = 404, msg = "Không tìm thấy hình ảnh để cập nhật." });
                }

                // Cập nhật giá trị Oder ID
                imageToUpdate.OderID = oderID;
                db.SubmitChanges();

                return Json(new { code = 200, msg = "Cập nhật Oder ID thành công." });
            }
            catch (Exception e)
            {
                // Xử lý lỗi và trả về thông báo lỗi
                return Json(new { code = 500, msg = "Lỗi khi cập nhật Oder ID: " + e.Message });
            }
        }

    }
}

LuxuryHotel/Areas/Reception/Views/Image/Edit.cshtml
@model List<LuxuryHotel.Models.Image>

@{
    ViewBag.Title = "Quản lý ảnh";
    Layout = "~/Areas/Reception/Views/Shared/LayoutAdmin.cshtml";
}

@section customStyles {
    <style>
        #page-edit-img {
            width: 100%;
            position: relative;
            display: flex;
        }

        #imageContainer {
            position: absolute;
            width: 60%;
            left: 10px;
        }

        #form-create-edit {
            position: absolute;
            width: 35%;
            right: 10px;
            display: none;
        }

        #item img {
            width: 100%;
            height: 100%;
            aspect-ratio: 1;
            cursor: pointer;
        }

        #item span {
            position: absolute;
            top: 1px;
            right: 20px;
        }

            #item span:hover {
                font-weight: 700;
                color: red;
                cursor: pointer;
            }
        #imageContainer img{
            border-radius:5%;
        }
    </style>
}

<input type="hidden" name="IDRoom" id="txtRoomID" value="@ViewBag.roomID" />
<button type="button" class="btn btn-success" onclick="showCreateForm()" style="width:80px; margin:20px">Create</button>

<div id="page-edit-img">
    <div id="imageContainer" class="row">
        <!-- Các hình ảnh sẽ được thêm vào đây -->
    </div>

    <div id="form-create-edit">


        @using (Html.BeginForm("Create", "Image", FormMethod.Post, new { enctype = "multipart/form-data", id = "uploadForm" }))
        {
            @Html.AntiForgeryToken()
            <input type="hidden" name="roomID" id="txtRoomID" value="@ViewBag.roomID" />
            <div class="form-group">
                <label for="editPriceFirstHour">Ảnh:</label>
                <input type="file" class="form-control" id="fFileUpload" name="fFileUpload" required>
            </div>
            <div class="form-group">
                <label for="editPriceOverTime">Ưu tiên:</label>
                <input type="number" name="" class="form-control" id="iOderID" min="1" required>
            </div>

            <!-- Các nút để submit hoặc đóng form -->
            <button type="button" class="btn btn-primary" onclick="submitEditForm()">Submit</button>
            <button type="button" class="btn btn-secondary" onclick="closeForm()">Close</button>
        }
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel">Chỉnh sửa ưu tiên</h5>
               
            </div>
            <div class="modal-body">
                <input type="number" class="form-control" id="editImageID" hidden>
                <label for="editOderID">Thứ tự ưu tiên:</label>
                <input type="number" class="form-control" id="editOderID" required min="1">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" id="btnClose">Đóng</button>
                <button type="button" class="btn btn-primary" onclick="updateOderID()">Lưu thay đổi</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            loadImages();
        });
        // Đóng modal khi nút Đóng hoặc close được nhấn
        $('#editModal').on('hidden.bs.modal', function () {
            // Xóa giá trị trong các trường input của modal khi modal được đóng
            $('#editImageID').val('');
            $('#editOderID').val('');
            $(this).modal('hide');
        });
        $('#btnClose').on('click', function () {
            // Đặt lại giá trị các trường input khi đóng modal
            $('#editImageID').val('');
            $('#editOderID').val('');

            // Đóng modal
            $('#editModal').modal('hide');
        });
        function loadImages() {
            var roomID = $('#txtRoomID').val();

            $.ajax({
                url: '/Reception/Image/GetImages',
                type: 'get',
                data: { roomID: roomID },
                success: function (data) {
                    if (data.code === 200) {
                        console.log(data);
                        var imageContainer = $('#imageContainer');
                        imageContainer.empty();

                        $.each(data.images, function (i, images) {
                            var imageDiv = $('<div class="col-lg-4 col-md-6 col-sm-6 col-xs-12" id="item">');
                            imageDiv.append(`<img src="/Admin/Images/Room/${images.ImagePath}" onclick="showEditModal(${images.ImageID},${images.OderID})" loading="lazy"  />`);
                            imageDiv.append(`<span onclick="deleteImage(${images.ImageID})">X</span></div>`);
                            imageContainer.append(imageDiv);
                        });
                    } else {
                        alert(data.msg);
                    }
                }
            });
        }

        function deleteImage(imageID) {
            $.ajax({
                url: '/Reception/Image/DeleteImage',
                type: 'post',
                data: { imageID: imageID },
                success: function (data) {
                    if (data.code === 200) {
                        loadImages();
                    } else {
                        alert(data.msg);
                    }
                }
            });
        }

        function showCreateForm() {
            $('#form-create-edit').show();
            $('#iOderID').val('1');
        }

        function closeForm() {
            $('#form-create-edit').hide();
        }

        function submitEditForm() {
        // Lấy giá trị từ các trường input
            var formData = new FormData();
            formData.append('roomID', $('#txtRoomID').val());
            formData.append('fFileUpload', $('#fFileUpload')[0].files[0]);
            formData.append('iOderID', $('#iOderID').val());
        // Thực hiện AJAX request để gửi dữ liệu đến server
        $.ajax({
            type: "POST",
            url: '@Url.Action("Create", "Image")',
            data: formData,
            contentType: false,
            processData: false,
            success: function (data) {
                // Xử lý kết quả thành công
                loadImages();
                alert("Form submitted successfully!");
                // Có thể thêm các hành động khác tại đây (chẳng hạn, làm mới trang, đóng form, vv.)
            },
            error: function (error) {
                // Xử lý lỗi
                alert("Error submitting form: " + error.statusText);
            }
        });
    }
        function showEditModal(imageID, oderID) {
            // Đặt giá trị Oder ID ban đầu của modal
            $('#editImageID').val(imageID);
            $('#editOderID').val(oderID);
            // Hiển thị modal
            $('#editModal').modal('show');
        }

        function updateOderID() {
            var newOderID = $('#editOderID').val();
            var ImageID = $('#editImageID').val();

            // Thực hiện AJAX request để cập nhật Oder ID trên server
            $.ajax({
                url: '/Reception/Image/UpdateOderID',
                type: 'post',
                data: { imageID: ImageID, oderID: newOderID },
                success: function (data) {
                    if (data.code === 200) {
                        // Đóng modal sau khi cập nhật thành công
                        $('#editModal').modal('hide');

                        // Tải lại danh sách hình ảnh
                        loadImages();
                    } else {
                        alert(data.msg);
                    }
                },
                error: function (error) {
                    alert("Error updating Oder ID: " + error.statusText);
                }
            });
        }
        

        

    </script>
}

LuxuryHotel/Areas/Reception/Views/Image/Index.cshtml
@{
    ViewBag.Title = "Quản lý Ảnh";
    Layout = "~/Areas/Reception/Views/Shared/LayoutAdmin.cshtml";
}

@section customStyles {
    @Styles.Render("~/Content/datatables")
    <style>
        .img-col {
            max-width: 100px;
        }

        .mgt {
            margin-top: 16px;

        }
     

        .row {
            width: calc(100% - 500px);
            
        }
       
    </style>
}

@section Scripts {
    <script>
        var dataTable = $('#tblRoomImg').DataTable({
            "searching": true,
            "ordering": true
        });

        function loadRoomImages(dataTable) {
            $.ajax({
                url: '/Reception/Image/GetRoomImages',
                type: 'get',
                success: function (data) {
                    if (data.code == 200) {
                        console.log(data);

                        // Kiểm tra xem dataTable đã được khởi tạo chưa
                        if (dataTable) {

                            // Xóa dòng cũ
                            dataTable.clear();

                            // Thêm dữ liệu mới
                            $.each(data.rooms, function (k, v) {
                                let s = '<tr id="' + v.RoomID + '">';
                                s += '<td style=" width: 15%;">' + v.RoomName + '</td>';
                                s += '<td style=" width: 550%;">' + getImages(getUrlImages(v.RoomID)) + '</td>';
                                s += '<td style="text-align: right; width: 15%;">' + getCount(getUrlImages(v.RoomID)) + '</td>';
                                s += '<td class="col-ms-3 text-right" style=" width: 15%;">';
                                s += '<button class="btn btn-sm btn-warning" name="update" onclick="editRoomImages(' + v.RoomID + ')"><i class="fa fa-pen-square" aria-hidden="true"></i></button>&nbsp';
                                s += '</td>';
                                s += '</tr>';
                                dataTable.row.add($(s));
                            });

                            // Tạo lại DataTable
                            dataTable.draw();
                        }
                    }
                }
            });
        }

        $(document).ready(function () {
            loadRoomImages(dataTable);
        });



        // Hàm này gọi phương thức API để lấy thông tin UrlImages từ Room
        function getUrlImages(roomID) {
            var UrlImages;
            $.ajax({
                url: '/Reception/Image/GetUrlImagesByRoom',
                type: 'GET',
                async: false, // Sử dụng synchronous để đảm bảo giá trị được trả về trước khi tiếp tục
                data: { roomID: roomID },
                success: function (data) {
                    console.log(data);
                    UrlImages = data.images;
                },
                error: function (error) {
                    console.log("Lỗi khi lấy thông tin UrlImages: " + error);
                }
            });
            return UrlImages;
        }

        // Hàm này trả về chuỗi HTML chứa các biểu tượng tiện ích
        function getImages(UrlImages) {
            var iconsHtml = '';
            $.each(UrlImages, function (i, images) {
                iconsHtml += '<img src="/Admin/Images/Room/' + images.ImagePath + '" loading="lazy" style="width:20px; height:20px; margin:5px" />';
            });
            return iconsHtml;
        }

        function getCount(UrlImages) {
            var count = 0;
            $.each(UrlImages, function (i, images) {
                count++;
            });
            return count;
        }
        function editRoomImages(roomID)
        {
            window.location.href = '@Url.Action("Edit", "Image")?roomID=' + roomID;
        }
    </script>
}

<div class="table-responsive mgt" >
    <table id="tblRoomImg" class="table table-striped"  cellspacing="0">
        <thead>
            <tr>
                <th>Tên Phòng</th>
                <th>Ảnh</th>
                <th>Số lượng Ảnh</th>
                <th class="col-ms-3 text-right">Các chức năng</th>
            </tr>
        </thead>
        <tbody>
            <!-- Dữ liệu của bảng sẽ được thêm ở đây -->
        </tbody>
    </table>
</div>